#!/usr/bin/env php
<?php

require 'require.php';

array_shift($argv);

$command = $argv[0];
$directives = $argv;

$watch = WatchCommand::detect($command);
$list = ListCommand::detect($command);
$stop = StopCommand::detect($command);

if ($watch) {
	$watch = new WatchCommand($directives);
} else if ($list || $stop) {
	if ($list) {
		$list = new ListCommand($directives);
	} else if ($stop) {
		$stop = new StopCommand($directives);
	}
}
